[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d81172315dabc43fcc7a8189d519619f46d89a24"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "b7e26b80d94d88f8b8b599f9981dde7b7329a24f4df5a9ca38474f42509fc369"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89a6b5ea2c9c21750d0a0f90dc82876319394f71"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "744f6ecd39c81489bc9a5455ffbf51ace1bd20ea22afeea0169d5c23f992be35"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35afb57b2e62f17bdd89d1071e5e2e17b8cf1271"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "9107390054b74c234a2a47a460e05ce407d0fdc2a24e53a22c1bece4546ec1a3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6631ce35694844a74bc54f791dbcf9cb7e9363fe"
os = "windows"

    [[CGAL.download]]
    sha256 = "0f90e7532b39d337cb8ad79248e735c69e8df15504c101481ebe234377e14f77"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd54aa218850a8048dc4b63ae1cf5cffb34ee71b"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "0f0717d393096568860e33056a080bec15116069bc1d0cfc967120c643e452b9"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.i686-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46723cb729ceaa7409a61c729abf6b3d3b6a9d69"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "edb50aeaa315ab9c3599624cc61212a089176bba22b865ef94846529ed507a45"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "577e6109072986515c4cb00ad0f66bf251ee8e0e"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "77ca5793f5c44b2984fa254eb6a88552f985b8c22bc9cc50fb82e1ae0af07880"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01cec6e76deaaab6f20f5100552f85b1f8b8a30b"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "297a508daefc7682dca15ba14dbabeed40e21e80095ada2f3df2255782f83f9d"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.i686-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be6ac93f1fb83f9ae98986d482ff538c27a7ac6e"
os = "macos"

    [[CGAL.download]]
    sha256 = "fd2d06928ac4cb37f714f70a6f18dab4bc423711adf43e989f535c4663b1922d"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "259531ed1754abc48d692d7787dc1350e3952b2e"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "8b7d1c05676ce1c8fa09e1fe724464463257f6fb200d75ecc53c329d554b1317"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.i686-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ebf9ffb3346ccdcbd9c1c2a6ab6e401b51034fe"
os = "windows"

    [[CGAL.download]]
    sha256 = "294e04d56d9df8c97794685895d5660f58fadca84a3dbb0d7065de35854c0639"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f93f5f439f08a5b758eff036a3c22e725259d86"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "c14fa930ef8eb6f748a9b627a5fef1672f80075a81553a298d2e109ca662c586"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53e6a705b45759453a94b80bfe078b4967a0fb47"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "dd2635b0c03a32f898397cbcc27be2c46c902194bfbf8083a0da8372ebe70e1e"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3ec28c884b7bd9ece7dddec99101a1efdb4e265"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "2a1fa2cc957c18e048679829d27798194f9c8270c74855523c4f0bfd1e023b84"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d412e840cd414838089fca3d9302cab62a192c1"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "20980918b4388153c5b1243d558973859de357aa4a17db1de567c6270bf18692"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a705558912b5fa690637b5d22e7967163b5b6077"
os = "macos"

    [[CGAL.download]]
    sha256 = "0c0ec0664f2ba00398c8f9db198013d16bbfa336c9d91266673d0e7ac60ec788"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64a6559101a664719106e8d78b54d792d7858832"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "4d1f6645275ad0ff0114b8fddd4cf5261fe6bffe4246fe77e5b612fb9e9afeac"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40a1b491f2dc8d461d799d6cb28e49c4568da502"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "d059e74bd843c0f3d8728734cc059b3ce5cedd72d2c56210c71fd38ed690cf50"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c37f3d0a49d7bce24a5fc6a67099fcc3703c30a"
os = "windows"

    [[CGAL.download]]
    sha256 = "9fea6bbff65802ac8542644f811345bda0d60fcf1a070b82991f1593843b76f8"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe4d274e98e0dd47c065ec42674d6888874de862"
os = "windows"

    [[CGAL.download]]
    sha256 = "22b9e4ba1510e7869babe03a93be6be05574ee5aed4d1435497ce0d7ac2e7bc8"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "476a0b7ed6c3666c17a03752c45eb1b12b35c76d"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "f9249cad7ecaf4a869e11c3d51f98e15607993972c2b2745229a65f9ba3d5234"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7bf136fdb5f81697b2b0b1095d2a27e184c4dec"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "73fee839aacb7e55bb1c9caa36ef9ed3273e81b6f2264ec9f0777e5c606ec9cf"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a724a76b742c18c64009e82d30e0c72047b55fb"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "3fd8ece12f3df759db4886e529886e338b1179b437531e1d253152d1653a87b0"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7923acfa79434bebb7cece74e6445f68c17e70de"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "8a7f0d38c7794ae7826c9bf355613b4bf0db7223fb60a979296f15f7c863d309"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60ee3fb64a4719df8c756781ef791b29f8ea7800"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "dba7fa152f57cec19554195f0a713365c168a3fbe577366f469b921066f70d81"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "957663cd47e84affac4356dad4527c0d63448364"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "4a47e61b3eb46424ddc0e66c059836452bfbecfba050907a5ab2f786a00330c3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+1/CGAL.v5.0.1.i686-linux-musl-cxx03.tar.gz"
