[[CGAL]]
arch = "i686"
git-tree-sha1 = "2dd837bf758eb4d60cbb95f07f882c11ea3b2928"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "f57bbcd1113e782a39b5d2a8d1fdddecf5261e6e0983839516eb3b9fe7447766"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.i686-linux-gnu.tar.gz"
[[CGAL]]
arch = "i686"
git-tree-sha1 = "5cd4db5e5ed98579c2271c5a65bc5379f48684da"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "f68ede7f0cb759c87c89b0923620b65de2b3efd45e6dab27cd88c74e1c002796"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.i686-linux-musl.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "fcf87ee8710d844414d28add6ba93ce65737708c"
os = "macos"

    [[CGAL.download]]
    sha256 = "54c829c8a2116b90223853fc2995b9ae94a3576ecf0dc7135246c6646550c4a7"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-apple-darwin14.tar.gz"
[[CGAL]]
arch = "powerpc64le"
git-tree-sha1 = "bce9dc088ccbe84c45845f52775f9b241684a5d5"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "d98c47a6184c9b204bde333b6dc106a018f9cbce3e4bd911c883564676ee063f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.powerpc64le-linux-gnu.tar.gz"
[[CGAL]]
arch = "aarch64"
git-tree-sha1 = "b840eddb1242f6bc90ceb2a2ce0ccbe2fe35be5e"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "794b724e2692ea33acb2282d9dbe775416f5b9bcb3f9c3dadaab5d981bc74144"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.aarch64-linux-gnu.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "23fe5c9edaabb3a8dcde4a4349bdea1f02bc963d"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "84df1f7de5d1a524557abc91df2853e6169b2aed69b3297721ef8e62ebfcbe4a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-linux-musl.tar.gz"
[[CGAL]]
arch = "aarch64"
git-tree-sha1 = "812b8d7832a20d32ea22b7afee4eb324ea778fc3"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "2f5417b13e7f7f938dd803ec6faeded0e10faa7353da9feb2a0a7aaef16abfb6"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.aarch64-linux-musl.tar.gz"
[[CGAL]]
arch = "armv7l"
git-tree-sha1 = "7bae59d686bd04fa4a14bf736395ad1eebfe05ba"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "6d2e2422319f00a3439bc082b547cc6b3ba842cc7bf27725620d3be6ee34bb8a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.arm-linux-musleabihf.tar.gz"
[[CGAL]]
arch = "i686"
git-tree-sha1 = "12613361f3c230caf1b735712437ae905505d5d8"
os = "windows"

    [[CGAL.download]]
    sha256 = "f1a836b7cae4e3c98d2638cb0cd4bcc485da33f55be3d1fc1c7dfa1abcdd02a3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.i686-w64-mingw32.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "7dfe93607f48d23cedb5edb4b57105bba9cbd08d"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "350b69ec0f614f70ff5a66c20516c999a4c2105531e88a8d932d20189d968ef2"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CGAL]]
arch = "armv7l"
git-tree-sha1 = "137f7c6c846f4ea79144d65bb0c729e0b3581568"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "60733d251691552fb16af0ac4b8f7b9ba47ea22bc8104e01176daac6e7357bd9"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.arm-linux-gnueabihf.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "cef9cc036e16fdbaa640257b464f6645fad4ccc0"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "7c3b94b8d54492c0f6689f5dffa7582b802122862196b4aa656cf2e2f400d0cc"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-linux-gnu.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "0a8ee87277df2969368cecff09316a66984b5aec"
os = "windows"

    [[CGAL.download]]
    sha256 = "abaf6ecd0246ec3c8afce18834f3c7a248e9d7fd9d77af7974004022df8d8fa7"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-w64-mingw32.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b0f0ae8a5e38271a282533e99c9f6624dd462c7"
os = "windows"

    [[CGAL.download]]
    sha256 = "1d5b9f6a50153503a1556cb0c9718a223c903e4b6ae5b0d633062fe33b6f9694"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e47f89592b916dc8a40f20b3c0aa397a75772fe2"
os = "windows"

    [[CGAL.download]]
    sha256 = "92116907987281324ea5993b72742e2c17b5d1104ff519eccb99f4dc61f0ebff"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13fbefa6c3cbf11ca859ada39a34673bc317dc59"
os = "windows"

    [[CGAL.download]]
    sha256 = "07c436afc387ebddeb5f73cd8c5fa240c253c1ffd15e82ecaa8dfd383a356144"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0774727d0457977adf03a0c62a6fa73d02a40c89"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "d78c0ff0640f9caab61aac5a213679faff66ff1544334d8c21594bb2790d1afe"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd2281f7556f4e612e34513d5edd19464f60ee9e"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "21e2fd3cfe6911b5888abea12510153a3a1756baf94d10199d0a6d07f43d476c"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b282807a5778cd60557f7dc59f8f2dae4690a3f5"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "3c5b4b965502d90eea074dac8e8e9ea87212cba5ad996b1ca6add3255a04c5b3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6c0ebe8bc4ed942d2706aff3ab340497f06e9fd"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "5b52e201ff62794466c90d97a913d45cce7f712bbff20f276e2a65624634ba39"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a075765e65f506d5614916f3ac94aa37bcfcc08a"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "8f6e93ee076ad11a0c18dbd1d7a6485dc31b3582b2df662ed2f011add1b9e11c"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.arm-linux-musleabihf-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f104f933c4414a6a3605d3b8c9d20a01adf27736"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "fdf8e6ccd09adbf1e6735ef37c7a1a9e17046d19d5888ba0a2252b2dfb15a6ba"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.i686-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89b15baade22e53fe5b6b66dfe04d9024d26d86b"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "84bc303100ca17e3108270af1cbd1a4f32dee560d4b2b753f6e48849de349415"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4697da50e6ab1db9da88dfd58d0f2185149a6a80"
os = "windows"

    [[CGAL.download]]
    sha256 = "bedae380b1008af623c344bbae5e1dd1ec1f14f542fce1dad7d11ee2239922fb"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "508b91e46a9b5421b020df96f04e1666e705026b"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "4607961c312721a3bdca8d05945f4c157ab38bff100a28014d4246737426d536"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.arm-linux-gnueabihf-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a5cb7f53f1d067f4c12abad5db6921d1ae91e9a"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "587f8551a1e1291ebe8d13bb0c45fc125bc4313fee257328caf701f9e38a0692"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.i686-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "972cb1accd578543a12ad907e730ab7260111718"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "0749bb1c0434b02f007a9ff944f739ee85a7891800278b93e560322f35da1acd"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68a4bb0d546e89dcf40ae8b62660e07fae551f08"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "0f45f3d6f89f0f216e5d1f438dc0aa70f138b81d03f09d95a7c51e14ab252c5a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.arm-linux-musleabihf-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8744f531c2491df71d7774356c72e8a706a0f41d"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "b80959ee8a4f38158aa397d8e61b004a32d15be14e2b64eefa8e7516b1f3cea0"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4f0bba4179a2ddabee448cb36efe9d9a9ac0cda"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "5e887405828244901750038d4ac3153bfd36950bb5466e9422fe0bc31c009814"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.i686-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78f2401b53bb0fcd3bf0f52547b4622e3ec9779b"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "192ce33e22e1d0b1540cd0a85995454c2ed945d569b8a2c3be01f191ac3cab9c"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a91135fd0e2723f76df49fcf9dc994754e23119"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "ccbbe3f35c444016a3d12cc9b636a077ac8a638cf48a0e95ff620a4d842b12cf"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3071788cac32033e21a157fd587e83a2d3fd9964"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "d4537907c232014f67837929e9206fdb4e9f83407364fdaa17bb7e6f6ad316f0"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c429db3b2344f126a8b03686ce0eaa63a1ed7a75"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "344b24e46e18b465bf394a07361ccec5d420aa95ee314f2b77bc6064d2e7747c"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.i686-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3477d9fcb12415f9a32915ceb443763fa08fdef0"
os = "macos"

    [[CGAL.download]]
    sha256 = "e84328a22ff53d14bf785f0a10fe9717a62b165835831e2c0f29c87c8f4997a7"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f78dfca74b8d5984b92a575164c8d09a5c755f55"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "1eb491177cff357baa8f4472211ffe89fdae99cf5fc39330cdba815696d97ca0"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4bee8604fa1c4759b3969d1beb285c8d1bccd1ed"
os = "macos"

    [[CGAL.download]]
    sha256 = "4279bb174459aa28eda7ce6e002a0a1e5d9f7c4d90a8c8811dc34d63d5663f57"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e62701ed1de3a6f671b0ac2d4a56daf3c62a445b"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "15e88edc167a16dd16953af27a144ecbe5aa50742e1565d6ac08dd1d716dddbc"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.arm-linux-gnueabihf-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd5179a03c376a0ae03f0dceab0b99907ad041a2"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "8f315d872474bcfe0a51b29da8107a58e0f99ab9d6a6e2f08e56942a3d9638dd"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+2/CGAL.v5.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
