[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "babe9f28239493307a3c6eebb5e676df1a8904db"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "bc99853de8316bc38f31123e6ff3092ab8817aab2bd1f77adf17b959f4fbc502"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.aarch64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a58ee53b3f3c06968b3039b3a4a8a99702943d8f"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "96db0a386886aec20579d3eb8a396972a6e9af97a11b0c2cbf0596bc6e00bed6"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3067d04df772bf71d6d5b1afcee695fd168622f2"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "8f8d444a7ad5844e866e84e4cc631c81275ead890147460b4559d19bbfbaf9cb"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.aarch64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8df815188c3fddb57cf12a245eeb08dd72875fd4"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "429bf11c7814454128d69c2d3ce3274178b5362e9f5992c600aa0e4fa56feefc"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.aarch64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33f2e596dbac59cac57fb5c7bba8fdfa14dc455b"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "86e100f330f7f82594cd5043cbf1ceae1e7b7d8638ad76a3a7196358407ee79f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d24545de4c4225a300aacae07a45b818e32e1d7c"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "d644148d5b0964f615c850aededc3685312457b73d846c530d64f53c533bdc9a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2a4fb4557fdc90e308af32164cacf4d15ba9117"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "e0f51fee5e6831d65bfa7249de20554bae7283dc490cb3b57b487a272b46232e"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd6e8529b55fd239e1b45c355c3393cdcf384ad6"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "b8eb2499f5f347a3aaaa3c7785b23f702256c1bf075849056d0590d72e83a7a1"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "524dc0bc343148586cb3db6319524c5a08e0c62c"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "c3faf676fdbab253bffbeaec918c3683a881fd7fb94c252519fc0ace2434841c"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.i686-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8d72dfb4b450db8bd320898df0dc5fd110c288d"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "4d86126df3015531bcb0fae77503f7619c3171bb945aa69be1d6160e5165c9d4"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.i686-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "500533ae5a11cd330aac4af422da237198b0b61c"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "e8a3bd49e488bf2fff0a894d0d6d8db146a80db0784f407e64ac5442e9b1afe4"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.i686-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0f87db8b241415c888914128179fbfbcd02363c"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "06cc8ae89ae7dbaf689537e05676c620605979d614b80071f88f4588aa28ff44"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.i686-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8513c824576f8b988066a2656dc1f037d7902f61"
os = "windows"

    [[CGAL.download]]
    sha256 = "4bf18e7abe7b3d7f735604b308ce82aa708c8ff0c5b14dacd86aec0ed59e3172"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.i686-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94deba1b359aa789bd461ad78a76c073e9936b27"
os = "windows"

    [[CGAL.download]]
    sha256 = "72285df67a500d8c67a2d3566bc8aac38d5e43fbbee26695897209e5dd55cbd1"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b96bad1289cf96a04b64a71deba624474131441"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "208bdcbc82f87303c3c3050844c7d9ba353a8c7718a929884ec5bf671b7cc994"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e3ff7ceac79e7d6da8b8eb1cafd63c5fa58fab0"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "52eec9165a2ef48fb67af13e90ff78e198f87a32afc4a25ad5d38b5c63aab8a3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eac4a448f8c936f06426d27eb3f74923bb508e73"
os = "macos"

    [[CGAL.download]]
    sha256 = "4a84d939305b5766cfd3f65b0f91c89757d648cc0f144e17723495529d439554"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65151d1a2f2669fbd1928afadf4082b1b68027f9"
os = "macos"

    [[CGAL.download]]
    sha256 = "8eb3481fc586cbd2337602b583f4bbc40f58c2aa8d9a44160baf0584b014023f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bd022d59b9be41224f554c11f4cdc296a1a7826"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "5e56c514656c753dd66df92c52a615eb4f022eede7196ab63be54ad39cd3c059"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3687d082236e1bf939b8524919fc84c97ff62761"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "0c53b1ea55b25741fc016eece5b83c760dfaf1e0e6b37feddeef4b72b75ec81b"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee76bb729bb7e018d3cf1fa02e086f36b358b452"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "7890e141f309bec142d722fd695f39b60f97ce7bd7e3e6fe93cef2a2cbe1c013"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b604545d05337e94b9aa0fb1fbc9656ced523224"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "8ebc5a238bbab6207d44561b366b92bc82d984028e77277985de434b26586776"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8014e261b0a1df0eae91f9fbae6c742c35f06dbe"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "270ce44c3eec31e2a6e9df19c2de5dca7c4ba1859566fc7352acbb0db6ed0e00"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54792f475a96b00d8f14af5cc8f48c67c4c6fdaf"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "1515c78f2940d36409a811f9d91a450c428c59bcc478fa38e693cf1b0fe58f5a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "289d658897c8bda367e6714868e44b27cb165b5b"
os = "windows"

    [[CGAL.download]]
    sha256 = "53c97ffde6829f0d565afd818f5e24355175cb02fe1d9a671f8c8a7e5a941ee5"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31f913c7ae082e9aa082cc97de5f67a4f6ef6362"
os = "windows"

    [[CGAL.download]]
    sha256 = "d632b5baa2de14365906ea7ae563a4513b54fccf6f3f2ee1a942facb90b3bf66"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.2+1/CGAL.v5.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
