[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "064552e910ab4807ace62cec46fb021e6ed52631"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "5b6db86b55620063681a46b9a99848998a889f5143c2e85b3d97e4bc00199779"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e95c31d4be274c0c1fc4fe3a930faa63b5d4ed91"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "0911b1c34a521f7108258144363d01084abf47ace2b6d0b3164827592d34c543"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d46cfd6b02a41e5e4dac8eaa9fc2451f7eabe4cd"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "97b77885064d3ad4e917951d03d24f472d238a01f4d150ff393c0deef6b3f865"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.aarch64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a441efd18769be168b7008c16b5827d91f98dc5"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "f741e58fb2eb59d976529d4c0c392d327145b947a14fbdedbac12a42767c4d98"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.aarch64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51eddcf2c241ca44c35a9a2389d9b7401a3133fa"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "deec562feef9b7572d3d95f54b2ba5218cf32d493245e9f86125f9d9d395d212"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b64b186102b291a426288a2bff883ab796d2a7f"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "0ccf1bb9308a0b45204ccf5c827a261673782acd57fd407d24d5c88604187610"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7d13e6b0e9aa24f0f7add30dcbf3ee5fc84b1c0"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "980752fcdddb3f5802b0f08642cda5e8abf1918399f645f593ed0f0035e71e14"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4c55e1834f39efc0f96e33228e34a877cb1ec32"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "4a3ff6c564667601ef0814ecae42163b1ec825b43bdd25ff485346a099e8507e"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be6fe8024f77aaa3ba8a4aa22d5ead90b7b08572"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "17770261e9b079d46ae49b7f68a9c9727059b068436d97a56a06c4b95c698811"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.i686-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6262b50fc4e25b9849c45a594a1137573efd15a7"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "96fbd393d36aefb5d3a070be6843eca5c9f833fecb77941bf2bdf9cdfbb4afa6"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.i686-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8c391f0caa1060f00509c52cbab39e6f970e8a0"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "f98d265af54a249746fb4d2d30d539e9f3beec333a434c1399855243de7e5a2f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.i686-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f21dd6f5ea27c8063420b5d1582df59d769dd31"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "77e9342cc34ff95a372a1d7be7a70350299a86dfb674f2cd1955ccb212fc1a8f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.i686-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17f84abbd00ede9ab08c1fec0834af0ad70c80a0"
os = "windows"

    [[CGAL.download]]
    sha256 = "fa666c59dc08aea72655c1ddc6bf0c6f133702eaa69f86cf3a448a92224804e0"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.i686-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c5c68442c25011dc4f01b9b6bc761488462672b"
os = "windows"

    [[CGAL.download]]
    sha256 = "bcaa6ffab9495249b3bc357575e04160a409018bcdd13fbcff890ca06e909486"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.i686-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8076ceab15dcdb723da61f9bef70da5df34acf6"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "1ba58e19c83fe32d5e5d3db42b1b00e40abe962b52bd678886621568751b53e4"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "802465ddaebb03051a37f62955a8fa8fdd66853a"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "acb106bee17db854ee30080dddb137f181b8f0ad08541a33a07964a81669fc4f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2952c9f52fb3c72768450ab128b283680cdb156"
os = "macos"

    [[CGAL.download]]
    sha256 = "f30433e4228a6f0d360b550874e35947643c6083ee6b749a37b85a98ff67c514"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56e2563dc54b0593b6aaa248f15f8c3747c831ce"
os = "macos"

    [[CGAL.download]]
    sha256 = "79dbab7448f8d07c97de8ff998c63f7dcef0d588e8a3f71ce43302c79b40670c"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7dc91eb58e06468b8d6a980db2a764347552eb46"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "1eddced2a3f0beb4a0db74721fe1fb968d31a911a25478c8490617c41de98ebe"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa26927be7e765bd97b17a7fcb162f03083dff25"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "03f1fca193b5a41aa82e677c48d56dc8aaccc9c2c0fe16f11a6537310e7987e5"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee2bbaf3e46ce84c3a69229f38cfdcc17e3dcebf"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "1e4b61904982d69ab6511ebd7138a54e34e9b028cd3959e0555f1b11077d4764"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "346814f3626bcb4d9ac155890acff904542ed95c"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "737d4ec73a71d7756baa0fdf1a98350de2990bc0eef2101bc242f49414377539"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "105734ae7fa0d875c822d1835f4ac1d092fe99df"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "0c3bd3276cd3005b3de552af33200530485c1022c95e647beb59627a5c6de031"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "927388b3dd9d5609007935daa0cfe48d85e37fcf"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "9094896833436d5dd838cfd130f3f2c2262437cd99d30a7aa934fc99e8a26e18"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43b406e927c424fa054a3eb456e7729b41f2abda"
os = "windows"

    [[CGAL.download]]
    sha256 = "2daa310b24e3dcd5c685fe3934d21235deea4c6e5c07148e5228b546bf896124"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d02c85c2bc0e2c176c1803fc9b289b1141b3c05a"
os = "windows"

    [[CGAL.download]]
    sha256 = "e42d0203668e1f2c8df6233615acc1955701e88a078b361b4806998399425d99"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.3+0/CGAL.v5.0.3.x86_64-w64-mingw32-cxx11.tar.gz"
