[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "415b5a83e09fc41c05d5a008b2b22f766f702799"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "65e8b9fcafa45e816df509f43ac0a64e955381e14bdd3b4fd60260ad2bfcbff1"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba05693adb2044064227d8591ae9ab4e290d44bf"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "c6c767f773e6a7cca5accdfa9ff371d4a4da65ca7e32b130d5e2adf9c11adc6d"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12dff1a81048ed9a2ecf5bb31ab8250d688391c6"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "e807d8f1c7342541d8f29a5644b33b9cf926eee31f12013e833648c7aa817db8"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "177ffcd693c16f97138c00d236469e8990f3c7c7"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "7a828ae894e024fea48b1e57e2dd5620e01cc8b0b1b5864c4b381a24f0da5b73"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b77461297f4deeae1cab26d152545bc81c56c08e"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "78503a66816c989cbabf4f8c3c36606cfb606ad7368bebd3582b48561371f37f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04bdbe825d6bed661ae49c97cb635726983aaa3e"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "682b529b9b92bfb8e00bf8c69a275b5553f7398a3fd1f64bf2f48f9d67be835d"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08cc4d2f4071052a1247fda327c5c3210c3f9a4e"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "e3a7619ac76e1aef1248877cbb4862348a44757148abaaf5d55bed3d9a849228"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ca4809698a38de64eee38b1aab8f61aff1c75bd"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "af8ae93c1f9f132577b35e922b79adbfca4ebedf0829126eaeddcc3533e86f78"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b27d08effaa46d9ec7e4623fd335a79990ccb205"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "89b9eb5d4acaa66df0faa3ba09d22da834a8ccf6fc639962735b8e3ecc9d5e4b"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.i686-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "504a761deb4021f5487d1d9c4c72b94b377a8e6f"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "c4e2955a22b08b61074cd27fef775c627082fb261234cdcae556ce55cff04ee2"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.i686-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c103172d36ee9ae04fd1aa2dcbcff0387cc1c76d"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "7d3d0d0c72585cfc338ec85ffc2399d218514c553eba30e6744d1b28f9741979"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.i686-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9471519b3c4aaac1f5e6ba20980099b2983a1f9a"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "6323b65fd23900c3c91fb6379b7d10da9d0ac4afd95a0dd66ae5c61fc0eeeba8"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.i686-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa9f2894e814f0b9ed3ec51d9ceff8049bc3b00e"
os = "windows"

    [[CGAL.download]]
    sha256 = "88f2baba09a2aeae3695f87445d3dc8363037bf70cce7bb90be27271fd3696e4"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b40b58a37d4faea5eba466e6d82aedc9f060ee4"
os = "windows"

    [[CGAL.download]]
    sha256 = "95ac7b36f039eac4c8a45e04f6dc303532050766a1ba84f4d2bcb22080fa633b"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38eb72db4cbe2520d682446c7c266a662036bff8"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "bde4fc5ec3df630ddf8e138f318fb6f4dfced8bd46411b3ca3a9545708dddd5e"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e62550f5371509620a2da64cca83c913c7fa8e91"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "489e393c9bb8ef1a6827bacb4a8e1aba1ae8dd337ab1abf77d219a3f5d834e90"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "ecdf201f351818fe357548123388d009c02af485"
os = "macos"

    [[CGAL.download]]
    sha256 = "9338d575dead85b7674ae1c526dd925cd302e8757950c76743b6388ab68952de"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.x86_64-apple-darwin.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3b13413eea7a60790f2b689954477d3ab8bbf00"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "5c9e6274f7f3868de06f1c53011a00d237faec3e18fe73884bb1879fbb051be5"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d9c23b2db623d936cf77733b925d7beacc63af7"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "16980ee1eb64693dea613fc7f2c72b64c3be83e6b0c451e8b6cc30f022fd7235"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be35a53eef1f1b48d30bd5dbe015c62b5f384d5a"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "f1a979a809799d46186eb08ea166a030c6fdb8ee8d150b66a4eab76c78d97297"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67fd0734496dce9714cc8d12113e97162f6830ac"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "ebae78762c2618726546d0d9ef39c67f63f1d70826f43c2d4f9dfe5e22662e60"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "188a5f233ae27077b45a0db25085edb024173896"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "9f4bb05919bd115a66fc45cec84a0c49bdfe32cc880df1c56650b89bec4feb9a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.x86_64-unknown-freebsd.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c803ae0db61fa8a5dc861eeee3410383e027624"
os = "windows"

    [[CGAL.download]]
    sha256 = "552709c9481b4037f586e8f18c9bace3fa4542f6e9779c5a188b773b0d64d06a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acb8726f391f04e1dea388749ac9cfef2dfd0f6c"
os = "windows"

    [[CGAL.download]]
    sha256 = "2829202dd1fd6582a7b535543e4d56e4e3b178fc1f30f3fb361873b909023e16"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.1+0/CGAL.v5.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
