[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb0ca83a3fac366742486492dbff66d3b7e2bac8"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "6d6b2a77847ff70d0650c354fdcb39be3e3e3e726e7af77c4cdcb8676e512bba"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2397c3c486e9c70b26131ed62394fbf0b5c6ae7"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "33356d5d4455bf35b018d1971cff962d5296e62daa037351d2fc83f7bb3e2978"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89f496e4161c232f43dd73b79599c0df669a05ad"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "f921753dc2c7263ac39ca4b3440757dc15994d88e881261043f9965ada4de30f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b483b7973529e590f747d661856af4fc4c32fe2a"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "3a2a6f9907b5f2807be2dd9f2fe676fce549526eb3961edbe79219d212603e00"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c63f54b06c53f05ac340ae8ee54f3e060ce8075"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "ad883fab25238b732cdc1ca2f1cd7ba578591a0d05472ef4e1c5e82cde7c86b8"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40797829f21c4be93b192cf716063fe31704915c"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "00920675943f28adf82d9fb92a6188c75278256b218cb57469f403bb8f6a0294"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f16d31c4ce9bd349216cccd3df68b43a15a48714"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "d72c54185efda4ad9f28aad7bb71a77ac4f0a7baa1e1a1edcbc71dd3f1676ecd"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ef109383a21571068e908de11b2a204dfe188d8"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "e481020396bcd6730da9e42eb7a7854f09f80601bd77d1516e159343c282bff8"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e68cfb663c630ef45945d5d48616db7825ed1c15"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "d101556caf55943ae4f37483dee35ee8778929805cccabd6112056c9282fdd58"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.i686-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b01bd4125eeba12d2e412609b023481b7fcb43db"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "5d39e1558a72d38ec1fd815724fe734a8053b1724f86e36e200afbd69f40c863"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.i686-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fcc32e0417add6407546ec510fb309194467884"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "f37ccac0a6f6c9f306ed891c0c9e5ffa8b301ce9217b13e132b8d16be25e5e28"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.i686-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6381f36d4cf496949bfb6a0391d582c09aee3e8a"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "e7b3fe316beba2c453930a0d2b1af1391b040c86070aeee9b5d00984630e3bfd"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.i686-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "305c271f20c0b90ff9a3235966a7abb477d1a745"
os = "windows"

    [[CGAL.download]]
    sha256 = "549f03b7d0c800fd69d5dc586ad88dacd76317e6ad00687e425b26c40c466930"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed30d04af7ddd770ecd637e57d699057e3138fac"
os = "windows"

    [[CGAL.download]]
    sha256 = "4e447a4bd1f88677c6a71b19eab6dae259a4d7aa312cd6a0c431c4cf6f5a3dc3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fa4b2fb863dcc2221326b593c08b6e4d0370dec"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "edb5033c7b7da708ac9aa769c355d5fe41700a581c5932c81532087ac03a4b2c"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76bf2b9323936937996aeb5bf73997f5f50fa036"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "a8523875e0055796e5c772bbf25b7b5693c13dd42f3d7451919cc857e4660f1a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "884faac599f81b4ecad3988c7a79c38e31d52066"
os = "macos"

    [[CGAL.download]]
    sha256 = "928c1aeae2644236538eb68f568799d128b6d5106bb8f0869e6c1956a1353c4e"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.x86_64-apple-darwin.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6671adbc676ea8c6c4c860f578be0bdc103bbd5"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "9bf636cdce84b71a02e4d5d355df0fb4a6ed7fba8dc14cc65e52cc94704290af"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "370ffe2d4fa6710a3393f5eb86600a6bd26cf140"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "9e40fb3dd49e102e968a975c6959e405ed62348b764fc491dc78f4025588668b"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb5d235a7a6c21567fc7ac17e84943db4ec1e896"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "b6f739e313833fc9b0b03c99277a1cbe34367edd7ca7183d0641c3b575ad86d1"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2cf7b1c8a7a8c85cd29f3b1f5421b2b6536c923"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "b1e805f3a187649780e31b6b917e13eaa5131a6c19d58365fed573ee01d88d96"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "31e16de5b99b32f97dac4228ab68e2c002a78249"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "b8556220d9809114cb97f6c370228325b6a4f3c29028835be21eac7db1bfee3d"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.x86_64-unknown-freebsd.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6631db37ed98b734e81b1ce8ae8ee844bdc2ab11"
os = "windows"

    [[CGAL.download]]
    sha256 = "5bc7d1696ba0cd19db1bdff99b70f8172a0e4ac89b2fce4af8e5f324820d835a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4caa0d19a931bd3e602510512a3ddbaff3ace197"
os = "windows"

    [[CGAL.download]]
    sha256 = "d245228512c98498badf3db0eb787f0d336948ccd870968d4f7132017b6b4d52"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.2.0+0/CGAL.v5.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
