[[CGAL]]
arch = "i686"
git-tree-sha1 = "2dd837bf758eb4d60cbb95f07f882c11ea3b2928"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "f57bbcd1113e782a39b5d2a8d1fdddecf5261e6e0983839516eb3b9fe7447766"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.i686-linux-gnu.tar.gz"
[[CGAL]]
arch = "i686"
git-tree-sha1 = "5cd4db5e5ed98579c2271c5a65bc5379f48684da"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "f68ede7f0cb759c87c89b0923620b65de2b3efd45e6dab27cd88c74e1c002796"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.i686-linux-musl.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "fcf87ee8710d844414d28add6ba93ce65737708c"
os = "macos"

    [[CGAL.download]]
    sha256 = "54c829c8a2116b90223853fc2995b9ae94a3576ecf0dc7135246c6646550c4a7"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-apple-darwin14.tar.gz"
[[CGAL]]
arch = "powerpc64le"
git-tree-sha1 = "bce9dc088ccbe84c45845f52775f9b241684a5d5"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "d98c47a6184c9b204bde333b6dc106a018f9cbce3e4bd911c883564676ee063f"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.powerpc64le-linux-gnu.tar.gz"
[[CGAL]]
arch = "aarch64"
git-tree-sha1 = "b840eddb1242f6bc90ceb2a2ce0ccbe2fe35be5e"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "794b724e2692ea33acb2282d9dbe775416f5b9bcb3f9c3dadaab5d981bc74144"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.aarch64-linux-gnu.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "23fe5c9edaabb3a8dcde4a4349bdea1f02bc963d"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "84df1f7de5d1a524557abc91df2853e6169b2aed69b3297721ef8e62ebfcbe4a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-linux-musl.tar.gz"
[[CGAL]]
arch = "aarch64"
git-tree-sha1 = "812b8d7832a20d32ea22b7afee4eb324ea778fc3"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "2f5417b13e7f7f938dd803ec6faeded0e10faa7353da9feb2a0a7aaef16abfb6"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.aarch64-linux-musl.tar.gz"
[[CGAL]]
arch = "armv7l"
git-tree-sha1 = "7bae59d686bd04fa4a14bf736395ad1eebfe05ba"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "6d2e2422319f00a3439bc082b547cc6b3ba842cc7bf27725620d3be6ee34bb8a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.arm-linux-musleabihf.tar.gz"
[[CGAL]]
arch = "i686"
git-tree-sha1 = "12613361f3c230caf1b735712437ae905505d5d8"
os = "windows"

    [[CGAL.download]]
    sha256 = "f1a836b7cae4e3c98d2638cb0cd4bcc485da33f55be3d1fc1c7dfa1abcdd02a3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.i686-w64-mingw32.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "7dfe93607f48d23cedb5edb4b57105bba9cbd08d"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "350b69ec0f614f70ff5a66c20516c999a4c2105531e88a8d932d20189d968ef2"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CGAL]]
arch = "armv7l"
git-tree-sha1 = "137f7c6c846f4ea79144d65bb0c729e0b3581568"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "60733d251691552fb16af0ac4b8f7b9ba47ea22bc8104e01176daac6e7357bd9"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.arm-linux-gnueabihf.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "cef9cc036e16fdbaa640257b464f6645fad4ccc0"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "7c3b94b8d54492c0f6689f5dffa7582b802122862196b4aa656cf2e2f400d0cc"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-linux-gnu.tar.gz"
[[CGAL]]
arch = "x86_64"
git-tree-sha1 = "0a8ee87277df2969368cecff09316a66984b5aec"
os = "windows"

    [[CGAL.download]]
    sha256 = "abaf6ecd0246ec3c8afce18834f3c7a248e9d7fd9d77af7974004022df8d8fa7"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.0+0/CGAL.v5.0.0.x86_64-w64-mingw32.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44858a7842f220f79c6797e63f9e89600c5ce1ef"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "57f69ffaa956db9b6f2258b53c5e705bf764d69ac49539ea7e5e3e786bfb0a15"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1178cf9ef30fc76941a78fa9cd21165732b49673"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "2d68172f42abb28f272b0f833586b3478ab0041233177f6c63e8c319f5e84a42"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d49a1a494bf456781cbfab941352a6a7f017765"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "4c609b1415a7b62ad19a467485e6c2d92293ae50347105649594307b13cf88a3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.i686-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d200a8e69646fbe95ba95602bd86e940f2357c6"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "8ff04146cbfdbc037697cef6e3e1c4475d9495bce89a5c02a4ddd3c9bd85dfed"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daa926d1b7307fe99f817e467f71b417de825454"
os = "macos"

    [[CGAL.download]]
    sha256 = "4bdaaa80f50529803e3f33bf4af7f8af2884503caccb992d2c79e2cf3d0c369a"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67809362829dc937f4e604e8a318e939aeb224ee"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "74063d3cf546d5ffeef92eb356f3a8b1a468be5de63389b95a2459b731e9cd24"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f8df27850f65daf7950b8ab7f4e3c6c72bf8a7f"
os = "windows"

    [[CGAL.download]]
    sha256 = "73f45c00d7bd650dd7bd9cb85cdf5464fc4dc1ff35e049454724c49299f8278b"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56e6b176f9faa4b0b110c6041239ea7a1e4f1e27"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "a3dee5033ebaec342fb23d2ce041f3b7227fd912b1f7a2d1feb9e3e50a484164"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11e16de2e21a4cc28fde7a992ce27f564f536965"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "21ed23f388cef0052fbe3420c003d56ccd65f023ed155126814cfe73c14d78d1"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e38b0be70f420f0adf6e17f621f44e103db8d987"
os = "macos"

    [[CGAL.download]]
    sha256 = "11d3a68a8cb0ca2febfb6fcd09224818d5fd0e346d794ae9173c1910cea58399"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "683510572b258679a6c9f74081da16d275dd92f5"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "568ee5c8750b6dea4a814654647a1b14c82398eeb7d4a8b9e6d54cc5530070ad"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e9d85e3e35cce0f9cd45f0d0c3379d09a7efd9d"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "ff788614ee1edbb67648d9411d6d3b1c4fc66e6905c77dfd96d1c1d29116021d"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b07b115d3a6c17f8b9638492cca07375c19ce976"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "39d2ecb256505d6edac4fc07057078bc64f41e609e66f3448a1816154c27d3c7"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e88ddc77e68a91a287a416d3e3defecf4c463067"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "3641425f1739a5a705ae0bb9e1893636f7e079b41a15ceb412c65e9294d39fa8"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a530152e585d0922568bf1244528d394009e91d"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "ded664d8acb031d39111142c99469c43b81f55e0a538bcabdd71fada5b33e8e8"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.i686-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b7dc17b30f7e81eebd441f3e0789e9a7f77311f"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "56e411e8bedf06c1a660abe2b48e66f52f1bc9b6e03eadc3d4cd59a20bdeadcb"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.i686-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c45124981b11afd93f6877316229e0c5978e28c8"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "d2122889acfcadeffacc19e4379d23dde313ce889aab4ab1cbde88f19cfd0fcc"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.i686-linux-musl-cxx11.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2da31d50f85b6078253dbfc1bd331fce5516ad58"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "b02ad82065e4c79284c173faf44d734232fcdea1fec7bb73f84b8909b523a8ad"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a4937b9486b87244a95698e03f616f63fe95d16"
libc = "musl"
os = "linux"

    [[CGAL.download]]
    sha256 = "160e1d7fc1325bf429abee40feb700cc15d400466277a24d2d791cc46a60e507"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7168cbebbb7af4525b8297117869b821ae05e0b9"
os = "windows"

    [[CGAL.download]]
    sha256 = "2fc70b98f0a8f29cbe681e7d3759ef9f94553365087899cd6df493bc3bb5ee75"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d36e322dc86a779cdc2d88602a60bb72724049b7"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "98214e362b4d9a3ab37f0b007674406a816683d1f1842c884f1306f225fe55ec"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[CGAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f812e8e1451e6c6476dbc36c759d58297a63652a"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "b6f9a2e39ab3602438867ed64b65ef06576a04cf5f54ae789327b6c7008d4293"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CGAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85eb9b93fecc0e87e8d609adfa117a846e47e628"
os = "freebsd"

    [[CGAL.download]]
    sha256 = "e7f9001b577721214f710d2e8f3f76bf573af51483d0e1f1f61323b5e1324d48"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0402ec09c5e36d7bfc6fbcd1933dd1a0c99e38eb"
os = "windows"

    [[CGAL.download]]
    sha256 = "2bdf4b67ab5c60e5c8aff81835d10b47214cc89f98ed46569a161dc28ea24556"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[CGAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d7aa5a026d90cd3bd1ccd72ba26feaaf7e0711e"
os = "windows"

    [[CGAL.download]]
    sha256 = "a67dc64a6ae8af31051f0a8ccc90979546230196358168155939bf55d3c9d5b3"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[CGAL]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f942c8848a6a0b853482681822228bf573f440ac"
libc = "glibc"
os = "linux"

    [[CGAL.download]]
    sha256 = "8c49193620267be06cd8edb917c872717d77ed261597d7cc3dab7a6d472d66dc"
    url = "https://github.com/JuliaBinaryWrappers/CGAL_jll.jl/releases/download/CGAL-v5.0.1+0/CGAL.v5.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
