# Autogenerated wrapper script for CGAL_jll for i686-w64-mingw32-cxx11
export libCGAL, libCGAL_Core, libCGAL_ImageIO

using boost_jll
using GMP_jll
using MPFR_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("CGAL")
JLLWrappers.@declare_library_product(libCGAL, "libCGAL.dll")
JLLWrappers.@declare_library_product(libCGAL_Core, "libCGAL_Core.dll")
JLLWrappers.@declare_library_product(libCGAL_ImageIO, "libCGAL_ImageIO.dll")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, GMP_jll, MPFR_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libCGAL,
        "bin\\libCGAL.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libCGAL_Core,
        "bin\\libCGAL_Core.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libCGAL_ImageIO,
        "bin\\libCGAL_ImageIO.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
