# Autogenerated wrapper script for CGAL_jll for x86_64-apple-darwin
export libCGAL, libCGAL_Core, libCGAL_ImageIO

using boost_jll
using GMP_jll
using MPFR_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("CGAL")
JLLWrappers.@declare_library_product(libCGAL, "@rpath/libCGAL.13.dylib")
JLLWrappers.@declare_library_product(libCGAL_Core, "@rpath/libCGAL_Core.13.dylib")
JLLWrappers.@declare_library_product(libCGAL_ImageIO, "@rpath/libCGAL_ImageIO.14.dylib")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, GMP_jll, MPFR_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libCGAL,
        "lib/libCGAL.13.0.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libCGAL_Core,
        "lib/libCGAL_Core.13.0.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libCGAL_ImageIO,
        "lib/libCGAL_ImageIO.14.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
